### ISSUE TITLE
‘make’ Errors

### ISSUE THREAD

**Issue by qixuema** [PRBonn/puma#12]
Thank you much for your great work!
And when I try to enter ‘make’ in the terminal, there was something happened as fellows. Can you help me find out what's wrong? I will appreciate it very much！Sincerely waiting for your reply！

![20220330112623](https://user-images.githubusercontent.com/58554118/160745454-73056a3a-b7e0-4b44-872b-ec0f0106d02c.png)

**Comment by nachovizzo** [comment]
Sorry for the late reply. Apparently, the Kitware people changed a public key without previous notice. Meaning that the image is now broken. I will update the docker images and let you know in this issue when the process is ready

**Comment by nachovizzo** [comment]
Done!, please check now again if it's working and please let me know ;)

**Comment by qixuema** [comment]
First of all, thank you very much for your reply. After I update the code, i enter ‘make’ in the terminal again. It may be that I haven't configured it properly, which leads to the problem still exists . I feel a little confused about this.
![7f0aff68ff723e172f4a3fc09ddf51b](https://user-images.githubusercontent.com/58554118/162112884-dc8e5df1-84fd-4cc1-bbb9-7bf5dfa9341d.png)

**Comment by nachovizzo** [comment]
Do `docker system prune -a` and then try again ;)

**Comment by qixuema** [comment]
wow, it's cool! Thank you so much! it works well.

**Comment by qixuema** [comment]
I'm sorry, the problem about “NO_PUBKEY” has arisen again. I tried to use ```docker system prune -a``` and make it again, but it failed. Did the key update or something else go wrong?  
I'm  looking forward to your reply.
![微信图片_20220511231003](https://user-images.githubusercontent.com/58554118/167884598-c8cdfb45-04b3-43d8-b93e-4736283a4c6f.png)

**Comment by nachovizzo** [comment]
This looks exactly like before. I just executed `docker system prune -a` and then make and it's working. The problem is that you still how somehow have an old image. I completely removed the custom version of cmake on 62a1837c0f, meaning that if your docker image is trying to fetch the `apt.kitware.com` repo, is because you have an old image.

**Comment by qixuema** [comment]
Sorry for the late reply.
I tried to remove all unused containers and images, leaving only my commonly used QQ and wechat. 
Then I pulled the latest code again and executed `docker system prune -a`, but the problem still appeared. Do I need to remove QQ and wechat?
![微信图片_20220512094845](https://user-images.githubusercontent.com/58554118/167976359-8f05a919-3c3e-45f5-a6a4-f32d32a90e50.png)
![微信图片_20220512094902](https://user-images.githubusercontent.com/58554118/167976360-6f8f2420-768a-4625-bf54-492bf0600aef.png)

**Comment by nachovizzo** [comment]
I'm not sure if that would help, I can also not reproduce the problem. Please try to build the `apps` container with this command `docker-compose build --no-cache apps`, on the root of the repository

**Comment by qixuema** [comment]
Sorry, I tried to execute the `docker-compose build --no-cache apps` command in the root directory, but the error still exists. Maybe my system is not set up or cleaned up. I'll think of another way. Thank you！
